// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcDRwO_HGpc0nLAf2MV1FMZr0MwSuWAQw',
    appId: '1:1065311486724:web:a85526ce9c0b5f15230651',
    messagingSenderId: '1065311486724',
    projectId: 'campuspulse-6ea48',
    authDomain: 'campuspulse-6ea48.firebaseapp.com',
    storageBucket: 'campuspulse-6ea48.firebasestorage.app',
    measurementId: 'G-MPBMQ0T7S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaOZm4Fhn049InnsSbXMQMbnuTb_JTbME',
    appId: '1:1065311486724:android:052df38e0c6fd312230651',
    messagingSenderId: '1065311486724',
    projectId: 'campuspulse-6ea48',
    storageBucket: 'campuspulse-6ea48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_bP6Bchl68zNBq_UzuCoKQmfW1Bv3WA',
    appId: '1:1065311486724:ios:61e9f831737b61fc230651',
    messagingSenderId: '1065311486724',
    projectId: 'campuspulse-6ea48',
    storageBucket: 'campuspulse-6ea48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj_bP6Bchl68zNBq_UzuCoKQmfW1Bv3WA',
    appId: '1:1065311486724:ios:61e9f831737b61fc230651',
    messagingSenderId: '1065311486724',
    projectId: 'campuspulse-6ea48',
    storageBucket: 'campuspulse-6ea48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcDRwO_HGpc0nLAf2MV1FMZr0MwSuWAQw',
    appId: '1:1065311486724:web:d300757f042c1da4230651',
    messagingSenderId: '1065311486724',
    projectId: 'campuspulse-6ea48',
    authDomain: 'campuspulse-6ea48.firebaseapp.com',
    storageBucket: 'campuspulse-6ea48.firebasestorage.app',
    measurementId: 'G-HSJM2S09XV',
  );
}
